package com.nefu.carbage.entity;

import java.math.BigDecimal;
import java.util.Date;

public class City {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.city_id
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    private Integer cityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.garbage_sum
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    private BigDecimal garbageSum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.recyclable
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    private BigDecimal recyclable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.other_waster
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    private BigDecimal otherWaster;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.kitchen_waster
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    private BigDecimal kitchenWaster;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city. harmful_waster
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    private BigDecimal harmfulWaster;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.recycle_sum
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    private BigDecimal recycleSum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.create_date
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.city_name
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    private String cityName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.city_id
     *
     * @return the value of city.city_id
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.city_id
     *
     * @param cityId the value for city.city_id
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.garbage_sum
     *
     * @return the value of city.garbage_sum
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    public BigDecimal getGarbageSum() {
        return garbageSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.garbage_sum
     *
     * @param garbageSum the value for city.garbage_sum
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    public void setGarbageSum(BigDecimal garbageSum) {
        this.garbageSum = garbageSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.recyclable
     *
     * @return the value of city.recyclable
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    public BigDecimal getRecyclable() {
        return recyclable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.recyclable
     *
     * @param recyclable the value for city.recyclable
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    public void setRecyclable(BigDecimal recyclable) {
        this.recyclable = recyclable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.other_waster
     *
     * @return the value of city.other_waster
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    public BigDecimal getOtherWaster() {
        return otherWaster;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.other_waster
     *
     * @param otherWaster the value for city.other_waster
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    public void setOtherWaster(BigDecimal otherWaster) {
        this.otherWaster = otherWaster;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.kitchen_waster
     *
     * @return the value of city.kitchen_waster
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    public BigDecimal getKitchenWaster() {
        return kitchenWaster;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.kitchen_waster
     *
     * @param kitchenWaster the value for city.kitchen_waster
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    public void setKitchenWaster(BigDecimal kitchenWaster) {
        this.kitchenWaster = kitchenWaster;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city. harmful_waster
     *
     * @return the value of city. harmful_waster
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    public BigDecimal getHarmfulWaster() {
        return harmfulWaster;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city. harmful_waster
     *
     * @param harmfulWaster the value for city. harmful_waster
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    public void setHarmfulWaster(BigDecimal harmfulWaster) {
        this.harmfulWaster = harmfulWaster;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.recycle_sum
     *
     * @return the value of city.recycle_sum
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    public BigDecimal getRecycleSum() {
        return recycleSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.recycle_sum
     *
     * @param recycleSum the value for city.recycle_sum
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    public void setRecycleSum(BigDecimal recycleSum) {
        this.recycleSum = recycleSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.create_date
     *
     * @return the value of city.create_date
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.create_date
     *
     * @param createDate the value for city.create_date
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.city_name
     *
     * @return the value of city.city_name
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.city_name
     *
     * @param cityName the value for city.city_name
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }
}