package com.nefu.carbage.entity;

public class Dicti {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dicti.area_id
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    private Integer areaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dicti.area_name
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    private String areaName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dicti.area_parent_id
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    private Integer areaParentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dicti.area_id
     *
     * @return the value of dicti.area_id
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dicti.area_id
     *
     * @param areaId the value for dicti.area_id
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dicti.area_name
     *
     * @return the value of dicti.area_name
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    public String getAreaName() {
        return areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dicti.area_name
     *
     * @param areaName the value for dicti.area_name
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    public void setAreaName(String areaName) {
        this.areaName = areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dicti.area_parent_id
     *
     * @return the value of dicti.area_parent_id
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    public Integer getAreaParentId() {
        return areaParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dicti.area_parent_id
     *
     * @param areaParentId the value for dicti.area_parent_id
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    public void setAreaParentId(Integer areaParentId) {
        this.areaParentId = areaParentId;
    }
}