package com.nefu.carbage.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Street {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column street.street_id
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    private Integer streetId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column street.garbage_sum
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    private BigDecimal garbageSum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column street.recyclable
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    private BigDecimal recyclable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column street.other_waster
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    private BigDecimal otherWaster;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column street.kitchen_waster
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    private BigDecimal kitchenWaster;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column street. harmful_waster
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    private BigDecimal harmfulWaster;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column street.recycle_sum
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    private BigDecimal recycleSum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column street.city_id
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    private Integer cityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column street.create_date
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column street.street_name
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    private String streetName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column street.street_id
     *
     * @return the value of street.street_id
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    public Integer getStreetId() {
        return streetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column street.street_id
     *
     * @param streetId the value for street.street_id
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    public void setStreetId(Integer streetId) {
        this.streetId = streetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column street.garbage_sum
     *
     * @return the value of street.garbage_sum
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    public BigDecimal getGarbageSum() {
        return garbageSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column street.garbage_sum
     *
     * @param garbageSum the value for street.garbage_sum
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    public void setGarbageSum(BigDecimal garbageSum) {
        this.garbageSum = garbageSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column street.recyclable
     *
     * @return the value of street.recyclable
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    public BigDecimal getRecyclable() {
        return recyclable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column street.recyclable
     *
     * @param recyclable the value for street.recyclable
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    public void setRecyclable(BigDecimal recyclable) {
        this.recyclable = recyclable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column street.other_waster
     *
     * @return the value of street.other_waster
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    public BigDecimal getOtherWaster() {
        return otherWaster;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column street.other_waster
     *
     * @param otherWaster the value for street.other_waster
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    public void setOtherWaster(BigDecimal otherWaster) {
        this.otherWaster = otherWaster;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column street.kitchen_waster
     *
     * @return the value of street.kitchen_waster
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    public BigDecimal getKitchenWaster() {
        return kitchenWaster;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column street.kitchen_waster
     *
     * @param kitchenWaster the value for street.kitchen_waster
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    public void setKitchenWaster(BigDecimal kitchenWaster) {
        this.kitchenWaster = kitchenWaster;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column street. harmful_waster
     *
     * @return the value of street. harmful_waster
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    public BigDecimal getHarmfulWaster() {
        return harmfulWaster;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column street. harmful_waster
     *
     * @param harmfulWaster the value for street. harmful_waster
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    public void setHarmfulWaster(BigDecimal harmfulWaster) {
        this.harmfulWaster = harmfulWaster;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column street.recycle_sum
     *
     * @return the value of street.recycle_sum
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    public BigDecimal getRecycleSum() {
        return recycleSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column street.recycle_sum
     *
     * @param recycleSum the value for street.recycle_sum
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    public void setRecycleSum(BigDecimal recycleSum) {
        this.recycleSum = recycleSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column street.city_id
     *
     * @return the value of street.city_id
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column street.city_id
     *
     * @param cityId the value for street.city_id
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column street.create_date
     *
     * @return the value of street.create_date
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column street.create_date
     *
     * @param createDate the value for street.create_date
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column street.street_name
     *
     * @return the value of street.street_name
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    public String getStreetName() {
        return streetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column street.street_name
     *
     * @param streetName the value for street.street_name
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    public void setStreetName(String streetName) {
        this.streetName = streetName;
    }
}