package com.nefu.carbage.mapper;

import com.nefu.carbage.dto.City30DTO;
import com.nefu.carbage.entity.City;

import javax.xml.crypto.Data;
import java.util.Date;
import java.util.List;

public interface CityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Integer cityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    int insert(City record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    City selectByPrimaryKey(Integer cityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    List<City> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    int updateByPrimaryKey(City record);

    List<City> getCurrentCity7Days(String city);

    List<City30DTO> getCurrent30DaysCountry();

    List<City> getCityRank(Date start);

    City getPieChartCity(String city);
}