package com.nefu.carbage.mapper;

import com.nefu.carbage.dto.StreetDTO;
import com.nefu.carbage.entity.City;
import com.nefu.carbage.entity.Street;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;

public interface StreetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table street
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Integer streetId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table street
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    int insert(Street record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table street
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    Street selectByPrimaryKey(Integer streetId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table street
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    List<Street> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table street
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    int updateByPrimaryKey(Street record);

    Street getStreetByCityIdAndName(@Param("cityId") int cityId, @Param("street") String street);

    City getPieChartCity(String city);


    //    List<Street> getStreetRank(Date start);
    List<Street> getStreetRank();

    List<StreetDTO> getIndexData();
}