package com.nefu.carbage.dto;

import lombok.Data;

import java.math.BigDecimal;
import java.util.Date;

/**
 * @Author: zhanglan61
 * @Date: 2020/4/2 21:54
 * @Version: 1.0
 */
@Data
public class CityIndexDTO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.city_id
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    private Integer cityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.garbage_sum
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    private BigDecimal garbageSum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.recyclable
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    private BigDecimal recyclable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.other_waster
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    private BigDecimal otherWaster;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.kitchen_waster
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    private BigDecimal kitchenWaster;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city. harmful_waster
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    private BigDecimal harmfulWaster;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.recycle_sum
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    private BigDecimal recycleSum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.create_date
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.city_name
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    private String cityName;



    private BigDecimal lng;

    private BigDecimal lat;



}
