package com.nefu.carbage.dto;

import com.nefu.carbage.entity.Street;
import lombok.Data;

import java.math.BigDecimal;
import java.util.Date;

/**
 * @program: carbage
 * @description:
 * @author: nefulan
 * @create: 2020-03-31 19:39
 **/
@Data
public class StreetDTO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column street.street_id
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    private Integer streetId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column street.garbage_sum
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    private BigDecimal garbageSum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column street.recyclable
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    private BigDecimal recyclable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column street.other_waster
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    private BigDecimal otherWaster;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column street.kitchen_waster
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    private BigDecimal kitchenWaster;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column street. harmful_waster
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    private BigDecimal harmfulWaster;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column street.recycle_sum
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    private BigDecimal recycleSum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column street.city_id
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    private Integer cityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column street.create_date
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column street.street_name
     *
     * @mbg.generated Thu Mar 26 12:31:26 GMT+08:00 2020
     */
    private String streetName;


    /**
     * 坐标
     */
    private BigDecimal lng;


    private BigDecimal lat;



}
